apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: dev
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
            - name: product-service
        image: product-service:v1
        imagePullPolicy: Never
        ports:
                - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: dev
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 80
    targetPort: 8000
