apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
data:
  # echo -n "cloudmart123" | base64
  password: Y2xvdWRtYXJ0MTIz
  # echo -n "cloudmart" | base64
  username: Y2xvdWRtYXJ0
  # echo -n "cloudmartdb" | base64
  database: Y2xvdWRtYXJ0ZGI=
